modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
logoFile = "icon.png"

[[mods]]
modId = "cobblemaxer"
version = "1.0.0"
displayName = "Cobble Maxer for Forge"
authors = "Dragomordor"
description = '''
Adds items that maximize (or randomize) the IV's, EV's and Level of Pokémon
'''

[[dependencies.cobblemaxer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemaxer]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemaxer]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "NONE"
side = "BOTH"
