modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
icon = "assets/cobblemizer/icon.png"

[[mods]]
modId = "cobblemizer"
version = "2.0.0"
displayName = "Cobblemon Customizer for Forge"
authors = "Dragomordor"
description = '''
Adds items that allow players to manipulate various stats and aesthetic characteristics of Pokémon within the game.
'''

[[dependencies.cobblemizer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemizer]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemizer]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.1,)"
ordering = "NONE"
side = "BOTH"
